# Has a separate flows for develop branch (automatic builds),
# Merge Request (automatic builds) and main branch Release builds (manual builds).
definitions:
  artifacts: &androidArtifacts # Section def
    - emulator.log
    - labencryptedstorage/build/reports
    - labencryptedstorage/build/outputs/androidTest-results
    - labencryptedstorage/build/outputs/logs
    - labencryptedstorage/build/outputs/**/*.aar
    - labencryptedstorage/build/outputs/**/mapping.txt
    - sample/build/outputs/apk/**/*.apk
  debug-emails: &debugEmails
    - harri.kirik@lab.mobi
  release-emails: &releaseEmails
    - harri.kirik@lab.mobi
  scripts:
    # Local setup
    - &stepLocalSetup
      name: Set up local properties and permissons
      script: |
        chmod +x gradlew
        echo "sdk.dir=$ANDROID_SDK_ROOT" > "$FCI_BUILD_DIR/local.properties"
    # Build DEBUG
    - &stepBuildDebug
      name: Build Android
      script: ./gradlew buildAll
    # Build RELEASE
    - &stepBuildRelease
      name: Build Android
      script: ./gradlew buildAll
    # Start emulator
    - &stepStartEmulator
      name: Launch emulator
      script: |
        cd $ANDROID_HOME/tools
        emulator -avd emulator &
        adb wait-for-device
    # Run tests
    - &stepRunTests
      name: Test Android
      script: |
        ./gradlew connectedAndroidTest
        result=$?
        adb logcat -d > emulator.log
        if [ $result -eq 0 ]
        then
          echo "Tests executed successfully"
        else
          echo "Tests failed"
          exit 1
        fi
    # Build PUBLISH
    - &stepBuildPublish
      name: Publish to Maven Central
      script: |
        echo $PUBLISH_PROPS | base64 --decode > publish.properties
        ./gradlew buildAndPublishRelease

# Flows
workflows:
  release-builds:
    name: Release builds for verification (main branch only)
    scripts:
      - name: Check 'main' branch
        script: if [ "$FCI_BRANCH" != "main" ]; then exit 1; fi
      - *stepLocalSetup
      - *stepBuildRelease
      - *stepStartEmulator
      - *stepRunTests
    publishing:
      email:
        recipients: *releaseEmails
    artifacts: *androidArtifacts
  publish-builds:
    name: Publish to Maven builds (main branch only)
    environment:
      groups:
        - publishing_props
    scripts:
      - name: Check 'master' branch
        script: if [ "$FCI_BRANCH" != "main" ]; then exit 1; fi
      - *stepLocalSetup
      - *stepBuildPublish
    publishing:
      email:
        recipients: *releaseEmails
    artifacts: *androidArtifacts
  develop-builds:
    name: Development builds
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: 'develop'
          include: true
          source: true
    scripts:
      - *stepLocalSetup
      - *stepBuildDebug
      - *stepStartEmulator
      - *stepRunTests
    artifacts: *androidArtifacts
    publishing:
      email:
        recipients: *debugEmails
  merge-requests:
    name: Merge requests
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: 'develop'
          include: true
          source: false
      cancel_previous_builds: true
    scripts:
      - *stepLocalSetup
      - *stepBuildDebug
      - *stepStartEmulator
      - *stepRunTests
    publishing:
      email:
        recipients: *debugEmails
        notify:
          success: false
